name: $(major).$(minor).$(Year:yy)$(DayOfYear).$(rev:rr)

variables:
- group: Top-2000-variable-group
- group: shared-infra
- template: version.yml
- name: major
  value: 6
- name: minor
  value: 4
- name: product
  value: 'TOP2000'

trigger: none
pr: none
  
stages:
- stage: AgentStart
  jobs:
  - job: AgentStartJob
    pool:
      name: At Home
    steps:
    - checkout: none
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm start --resource-group CHR-RG-ABA-PRD-WE --name CHR-VM-ABA-PRD-WE'

- stage: Build
  jobs:
  - job: UWPBuild
    pool:
      name: uwp-agent
    steps:
    - template: app/build.yml

- stage: AgentShutdown
  dependsOn: Build
  jobs:
  - job: AgentStutdownJob
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: none
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureConnection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az vm stop --resource-group CHR-RG-ABA-PRD-WE --name CHR-VM-ABA-PRD-WE
          az vm deallocate --resource-group CHR-RG-ABA-PRD-WE --name CHR-VM-ABA-PRD-WE

- stage: Release
  dependsOn: Build
  jobs:
  - job: ReleaseUWP
    pool:
      name: At Home
    steps:
    - template: app/uwp-release.yml
  - job: ReleaseAndroid
    pool:
      name: At Home
    steps:
    - template: app/android-release.yml